### PR TITLE
Bring Nim to C speed

### PR DESCRIPTION
**Pull request by mratsim**
This brings Nim from 
```
$ time build/bench
331665

real    0m1.222s
user    0m1.193s
sys     0m0.013s
```

to

```
$ time build/bench
331665

real    0m0.672s
user    0m0.654s
sys     0m0.012s
```

on my machine (i5-5257U dual core 2.7Ghz Broadwell)

### CODE REVIEW

**Comment by Yardanico** [comment]
Also it seems that adding flto slowed down Nim (previous results in readme were 0.55 for markAndSweep and 0.95 for default GC)

**Comment by frol** [comment]
@Yardanico That is not LTO, that was a pity bug in the benchmarking code which was fixed in https://github.com/frol/completely-unscientific-benchmarks/commit/ee670ededbac9043e36560c3fa6cbd76c8dddb83

**Comment by Yardanico** [comment]
@frol ah, ok :)

**Comment by frol** [comment]
Please, fix the conflict. It seems that after you fix it, we will see the diff to be only around `{.noinit.}`. While I have no idea what that means, it doesn't look to me like something that one would write on a day-to-day basis in production code.

**Comment by mratsim** [comment]
Basically there is an issue currently in the Nim GC, that triggers it twice when the resulting value is a reference type: one when the Nim sees the result value (cancelled by noInit) and a second time when it's constructed.

I'm fixing the conflict, but seems like I will have to do it from Github interface from my editor it creates new conflict :/.

**Comment by mratsim** [comment]
It should be good to go now.

**Comment by frol** [comment]
> This branch cannot be rebased due to conflicts

**Comment by Yardanico** [comment]
@frol 
image

**Comment by mratsim** [comment]
Maybe refresh the page?

**Comment by mratsim** [comment]
Some screenshots about the difference on the code generated:

Before:



After:



genericReset is the code to reset a ref object to pristine state, which is not needed because we always construct the object completely.

**Comment by frol** [comment]
I see you merged master over your branch... Please, consider using `git pull --rebase upstream master` the next time. It is hard to even review your changes on GitHub as this PR now includes the changes that are already in the master.

**Comment by mratsim** [comment]
It's strange, I cherry-picked just the Nim changes, sorry :/

**Comment by Yardanico** [comment]
@frol what about nim devel? :)

**Comment by mratsim** [comment]
Ah right, the {.noInit.} pragma is ignored on Nim stable due to this regression: https://github.com/nim-lang/Nim/issues/7743

**Comment by frol** [comment]
Well, guys, we are all on stable, I spent the whole day only dealing with stable compilers, and I certainly don't want to maintain all the modifications and tricks with unstable/dev releases. The original idea of the benchmark was to see what we can write in a reasonable time without doing obviously stupid things (e.g. we missed `-d:release` and used `--opt:speed` instead in the original version of the benchmark).

**Comment by mratsim** [comment]
No problem, then I'll reopen a new PR once the new Nim stable hits.

**Comment by PMunch** [comment]
> Well, guys, we are all on stable, I spent the whole day only dealing with stable compilers, and I certainly don't want to maintain all the modifications and tricks with unstable/dev releases.

Most Nim users tend to use the dev version anyways, there's always neat stuff on those that haven't made it into a release yet. Plus with @mratsims changes and a few changes of my own I was even able to bring the Nim version with markAndSweep down to under C++ raw pointer speed.

**Pull request closed without merging**
