### PR TITLE
D noruntime/betterC implementation

### PR DESCRIPTION
**Pull request by edmundsmith**
This includes another D implementation, adapted from the first, which does not use the D runtime. Instead, it uses the C stdlib only. This means that there is no garbage collection and the executable is much smaller. 

It also has the `merge(Node*, Node*)` function transformed to be tail-recursive to match the existing split function, giving a considerable (~5-8%) speedup. This tail-recursive modification is independent of having a runtime or not, so would bring the same speedup to the other implementation if desired.

### CODE REVIEW

**Comment by frol** [comment]
@edmundsmith Thank you! This seems to go beyond "naive" implementation, though, but given it outperforms C++ with raw pointers (D manages to finish in 0.20s while C++ raw pointers version does it in 0.21s), I am eager to add it to the table (while it has a bit of "black magic"). Yet, your solution seems to not to release memory, it eats 11MB of RAM. This might be the secret of the speed... I don't consider such memory management as a fair play, though :)

**Comment by frol** [comment]
Increasing the number of benchmark iterations by 100, your D solution consumed 1GB of RAM. That is not a good solution :)

**Comment by edmundsmith** [comment]
Oh ok, I'll check that over. I thought that it'd been freed, I'll valgrind it to find why that is

**Comment by edmundsmith** [comment]
I think the runtime `.destroy()` call in `erase` was being turned into a no-op, so I created my own next to `make!T` which actually performs cleanup properly now

**Comment by frol** [comment]
That seems to have fixed the memory issue. Compiling D statically, I squeezed another 0.005, so this D solution compiled with the following options manages to run in 0.198s (the best run) while C++ raw pointers solution does it in 0.211s (the best run):

```
ldc2 main_nort.d -O3 -release -Xcc -flto -Xcc -s -static -of=main-nort-ldc
```

**Comment by frol** [comment]
Thank you for this state of the art solution! :)

**Pull request merged**
