### PR TITLE
Use -d:release for Nim

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Yardanico** [comment]
@frol can you merge this and re-run benchmark? Nim will be much faster with that :)

**Comment by frol** [comment]
I am so sorry for that! I will update the numbers ASAP!

**Comment by PMunch** [comment]
You might want to run with `--gc:markAndSweep` as well as it is quite a bit faster.

**Comment by frol** [comment]
I will give it a try!

**Comment by Yardanico** [comment]
@frol also you can use clang with Nim:
`nim c -d:release --cc:clang file.nim`
You can add both GCC/Clang results (they probably would differ)

**Comment by frol** [comment]
@Yardanico clang makes it slower:

| Options | Time, seconds | Memory, MB |
| --------- | ------------|  ------------- |
| --opt:speed | 4.0 | 0.5 |
| -d:release | 0.95 | 0.5 |
| -d:release --gc:markAndSweep | 0.55 | 5 |
| -d:release --gc:markAndSweep --cc:clang | 0.6 | 5 |

Notice the memory usage. Is that expected?

I have updated the results!

**Comment by narimiran** [comment]
@frol can you keep both versions in the tables? One with `-d:release` (for low memory) and the other with `-d:release --gc:markAndSweep` (for maximum speed).

**Comment by PMunch** [comment]
> Notice the memory usage. Is that expected?
The different GCs use different amounts of memory. I don't have the memory checking utility installed, would be interesting to run it with all the different GCs and see what the performance/memory balance between each was.

**Comment by frol** [comment]
@narimiran Done!

**Comment by PMunch** [comment]
Not sure why you are seeing so high memory usage rates. I installed cgmemtime and these are my results from all the different GCs: https://i.imgur.com/1Xz3Elo.png

**Comment by frol** [comment]
It seems that `object` vs `ref object` is a big deal, it is 376 KB now!

`-d:release --gc:markAndSweep` now has the lowest time and memory footprint! Should I drop the line representing the results for `-d:release` without `--gc:markAndSweep` from the main README?

**Comment by PMunch** [comment]
Well, `markAndSweep` isn't the default gc, so it makes sense to show both. But if you feel that it adds unnecessary clutter I wouldn't be opposed to just showing `markAndSweep`. You could also try the other GCs as well, as you can see from my graph the `regions` GC is potentially even better.

**Comment by PMunch** [comment]
It makes sense that using objects vs. ref objects makes a bit of a difference. Objects are more or less the same as a struct, and will be allocated on the stack. This means that as soon as the calling proc returns the memory is freed, but it might end up costing you some memory copying if you're not careful. A `ref object` on the other hand is again like a struct, but this time allocated on the heap. These will live on until the garbage collector figures out that they are no longer in use and will free them. What you are seeing here is that the object I changed from `ref` to a simple object is only used to pass multiple return variables (we could also have used a tuple for this, or an array of static length 3). This means that all these object are no longer floating around on the heap waiting for garbage collection. If we turn off the garbage collector completely with `--gc:none` we can see that our memory consumption skyrockets to (on my machine) 41MiB as none of these are ever cleared. By simply changing them to use `object` instead of `ref object`, still compiling with `--gc:none` the memory consumption drops to 504 KiB. So it's not the garbage collector using more memory, it's just that we allocate a lot of memory on the heap by using `ref object` which then have to be GC'ed away. To learn more about how objects and references work in Nim you can read my post on it [here](https://peterme.net/nim-types-originally-a-reddit-reply.html).

**Comment by frol** [comment]
We have just uncovered another pity [bug in Nim benchmark implementation](https://github.com/frol/completely-unscientific-benchmarks/commit/ee670ededbac9043e36560c3fa6cbd76c8dddb83). Testing the resulting code again, the memory footprint jumped to 5MB using swapAndSweep GC. Could you, please, confirm that is the case?

Another question I couldn't find an answer to is how to enable LTO for Nim? We are going to enable it for all the languages.

**Comment by Yardanico** [comment]
@frol you should pass arguments to the C compiler with --passC and --passL (you can look on how to use them in the docs).

**Comment by PMunch** [comment]
@frol, running it on my machine I only see a jump to 768KiB.. I'll investigate further and see if I can get it back down

**Comment by Yardanico** [comment]
@frol Can you also try with Nim devel? If you don't want to compile it manually you can use choosenim.

**Comment by PMunch** [comment]
Ah yes, it turns out that I do in fact get 5MiB when using Nim 0.18.0, using the devel version drops it to 768KiB

**Pull request merged**
