### PR TITLE
Improve Haskell version in both readability and performance.

### PR DESCRIPTION
**Pull request by Jaak**
The pattern "type FooCell = Maybe Foo; data Foo = ..." is usually
avoided in Haskell with just using recursive data type. Also strict
tuples and unboxed data is rarely used in practice.

Unfortunately still using Strict language. Could not reach quite the
same performance without it. Requires some actual performance analysis.

### CODE REVIEW

**Comment by frol** [comment]
@FranklinChen @314eter Could you, please, provide any comments to this PR? I am completely incompetent in Haskell.

**Comment by frol** [comment]
@Jaak Thank you for the improvements!

@FranklinChen Thank you for your thorough review!

**Comment by Jaak** [comment]
Thank you for review!

Yes, that's absolutely true that strictness annotations and `UNBOX` are idiomatic Haskell. I was merely a bit set back and wondered if it is possible to achieve similar levels of performance without those (and unboxed tuples).

Generally in benchmark shootouts all readability is optimized away in favour of performance. I enjoyed the fact that this code tries to be in the spirit of what a programmer would actually write if performance were not of utmost importance.

**Comment by frol** [comment]
I have just updated the scoreboards!

**Pull request merged**
