### PR TITLE
Update D noRT version, now compiles without runtime linked

### PR DESCRIPTION
**Pull request by edmundsmith**
This removes the runtime from the LDC compilation of `d/main_nort.d`, making the binary around 12.9k on my machine (Kubuntu 17.10). It also changes merge/3 to match the faster Nim version, gaining a slight speedup, as well as trivially templatising the split and merge functions, also giving a couple of ms speedup.

### CODE REVIEW

**Comment by frol** [comment]
What is the speed up you get from this?

**Comment by edmundsmith** [comment]
It's like 2-3%, but importantly, the binary size is much smaller thanks to the runtime not being included at all (370k -> 12.9k)

**Comment by edmundsmith** [comment]
Which `ldc2` version are you on? For reference, mine gives

    $ldc2 --version
    LDC - the LLVM D compiler (1.2.0-beta2):
    based on DMD v2.072.2 and LLVM 4.0.0
    built with LDC - the LLVM D compiler (1.2.0-beta2)
    Default target: x86_64-unknown-linux-gnu
    Host CPU: skylake
    http://dlang.org - http://wiki.dlang.org/LDC
  
    Registered Targets:
      x86    - 32-bit X86: Pentium-Pro and above
      x86-64 - 64-bit X86: EM64T and AMD64

**Comment by edmundsmith** [comment]
But it might be a case of adding another line into the version(LDC) block:

`__gshared void* _d_dso_registry;` - maybe see if this works for you

**Comment by frol** [comment]
```
$ ldc2 --version
LDC - the LLVM D compiler (1.9.0):
  based on DMD v2.079.1 and LLVM 6.0.0
  built with LDC - the LLVM D compiler (1.9.0)
```

**Comment by edmundsmith** [comment]
Hmm, this may need reverting then. I'll try with a newer LDC, see what's changed.

**Comment by frol** [comment]
If there is no fix in a few days, I will revert it, but I will keep it as is for now.

Thank you for your contribution!

**Comment by edmundsmith** [comment]
Does `ldc2 -betterC main_nort.d -O3 -release` or `ldmd2 -betterC main_nort.d -O -release` work for you? I can't reproduce the bug with LDC 1.10, although 1.10 renders the `__gshared void _d_eh_resume_unwind(void*) { return ;};__gshared void* _d_dso_registry;` bit unnecessary for me (only needing to keep _d_eh_personality)

**Comment by frol** [comment]
`-betterC` did the trick! See the updated stats.

**Pull request merged**
