### PR TITLE
Some notes on Haskell

### PR DESCRIPTION
**Pull request by FranklinChen**
Changed the build to allow adjustment of runtime parameters, e.g. for garbage collection, to speed things up.

### CODE REVIEW

**Comment by frol** [comment]
> 3 MB total memory in use

vs

> 131 MB total memory in use

Well, that is, basically, Java :)

**Comment by frol** [comment]
Does this new `rtsopts` flag improve performance?

**Comment by FranklinChen** [comment]
No, `rtsopts` does not improve performance. If anything, it just very slightly degrades it because it provides hooks for the runtime parameter tweaking.

**Comment by FranklinChen** [comment]
But running an `rtsopts`-compiled binary definitely improves performance as in the provided example of reducing GC.

**Comment by frol** [comment]
That is what I guessed. Given we are here for performance and not tunning, I don't see any point to hurt the performance. Is there a Wiki describing this technique? I would suggest to add this valuable information only to the README file and don't make the changes to the configs.

**Comment by FranklinChen** [comment]
The effect of compiling `rtsopts` is negligible on the performance of a binary that doesn't alter the default runtime parameters (maybe 1% in my experience); I had simply forgotten to put it into the initial build. Since Java and other GC-ed languages seem to have been run with performance-enhancing parameters, it seems reasonable to allow Haskell to as well. The RTS is documented at https://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/runtime_control.html

**Pull request merged**
